--liquibase formatted sql

--changeset sokolovRA:create_table_ads

create table ads
(
    id          bigint generated by default as identity primary key,
    title       varchar(255),
    description varchar(255),
    price       integer,
    author_id   bigint references users (id),
    image_id    bigint references image (id)
);