--liquibase formatted sql

--changeset sokolovRA:create_table_comment

create table comment
(
    id           bigint generated by default as identity primary key,
    created_at   varchar(255),
    text_comment varchar(255),
    author_id    bigint references users (id),
    ads_id        bigint references ads (id)
);