--liquibase formatted sql

--changeset sokolovRA:create_table_image

create table image
(
    id         bigint generated by default as identity primary key,
    file_size  bigint,
    media_type varchar(255),
    data_image bytea
);