

--liquibase formatted sql

--changeset sokolovRA:create_table_users

create table users
(
    id                      bigint generated by default as identity primary key,
    first_name              varchar(255),
    last_name               varchar(255),
    email                   varchar(255),
    password_authorizations varchar(255),
    phone                   varchar(255),
    city                    varchar(255),
    reg_date                timestamp,
    image_id                bigint references image (id),
    role_authorizations     varchar(255)
);